# Generated by Django 2.1.4 on 2020-01-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(max_length=10)),
                ('xm', models.CharField(max_length=10)),
                ('nl', models.CharField(max_length=3)),
                ('xb', models.CharField(max_length=4)),
                ('yx', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 's',
                'managed': False,
            },
        ),
    ]
